apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  namespace: chat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      name: mongodb-pod
      namespace: mongodb
      labels:
        app: mongodb
    spec:
      containers:
      - name: chatapp-mongodb
        image:  pranjalkumar09/chatapp-mongodb:latest
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          value: root
        - name: MONGO_INITDB_ROOT_PASSWORD
          value: root
      volumes:
      - name: mongodb-pv
        persistentVolumeClaim:
          claimName: mongodb-pvc
        