  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: my-node-app
  spec:
    replicas: 2
    selector:
      matchLabels:
        app: node-app
    template: 
      metadata:
        labels:
          app: node-app
      spec:
        containers:
        - name: node-app
          image: pranjalkumar09/webapp-demo:01
            