apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nodedb-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nodedb-app
  template: 
    metadata:
      labels:
        app: nodedb-app
    spec:
      containers:
      - name: nodedb-app
        image: pranjalkumar09/node-mongo-db:01
        ports:
        - containerPort: 3000
        env:
        - name: MONGO_URI
          value: "mongodb://mongo:27017/mydatabase"
      - name: mongodb
        image: mongo:latest
        ports:
        - containerPort: 27017


---
apiVersion: v1
kind: Service
metadata:
  name: service-my-nodedb-app
spec:
  selector:
    app: nodedb-app
  ports:
  - name: http
    port: 8080
    targetPort: 3000
  type: LoadBalancer
