
kind: Deployment
apiVersion: apps/v1
metadata:
  name: apache-deployment
  namespace: apache
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache
  template:
    metadata: # Corrected indentation
      labels:
        app: apache
    spec:
      containers:
        - name: apache
          image: httpd:2.4 # Fixed image tag
          ports:
            - containerPort: 80
          resources: # Fixed resource requests/limits structure
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              cpu: 500m
              memory: 512Mi
